In [50]:
import time
import pandas as  pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [51]:
dataset=pd.read_csv('dataset/Training.csv')
pd.set_option('display.max_columns', None)  # or use a specific number if you have too many columns
pd.set_option('display.max_colwidth', None) 

In [52]:
dataset


itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      muscle_wasting  vomiting  burning_micturition  spotting_ urination  \
0                  0         0                    0                    0   
1                  0         0                    0                    0   
2                  0         0                    0                    0   
3                  0         0                    0                    0   
4                  0         0                    0                    0   
...              ...       ...                  ...                  ...   
4915               0         1                    0                    0   
4916               0         0                    0                    0   
4917               0         0                    1                    0   
4918               0         0                    0                    0   
4919               0         0                    0                    0   

      fatigue  weight_gain  anxiety  cold_hands_and_feets  mood_swings  \
0           0            0        0                     0            0   
1           0            0        0                     0            0   
2           0            0        0                     0            0   
3           0            0        0                     0            0   
4           0            0        0                     0            0   
...       ...          ...      ...                   ...          ...   
4915        0            0        0                     0            0   
4916        0            0        0                     0            0   
4917        0            0        0                     0            0   
4918        0            0        0                     0            0   
4919        0            0        0                     0            0   

      weight_loss  restlessness  lethargy  patches_in_throat  \
0               0             0         0                  0   
1               0             0         0                  0   
2               0             0         0                  0   
3               0             0         0                  0   
4               0             0         0                  0   
...   

In [53]:
dataset.shape

(4920, 133)

In [54]:
dataset.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  muscle_wasting     vomiting  burning_micturition  \
count       4920.000000     4920.000000  4920.000000          4920.000000   
mean           0.021951        0.021951     0.389024             0.043902   
std            0.146539        0.146539     0.487578             0.204899   
min            0.000000        0.000000     0.000000             0.000000   
25%            0.000000        0.000000     0.000000             0.000000   
50%            0.000000        0.000000     0.000000             0.000000   
75%            0.000000        0.000000     1.000000             0.000000   
max            1.000000        1.000000     1.000000             1.000000   

       spotting_ urination      fatigue  weight_gain      anxiety  \
count          4920.000000  4920.000000  4920.000000  4920.000000   
mean              0.021951     0.392683     0.023171     0.023171   
std               0.146539     0.488397     0.150461     0.150461   
min               0.000000     0.000000     0.000000     0.000000   
25%               0.000000     0.000000     0.000000     0.000000   
50%               0.000000     0.000000     0.000000     0.000000   
75%               0.000000     1.000000     0.000000     0.000000   
max               1.000000     1.000000     1.000000     1.000000   

       cold_hands_and_feets  mood_swings  weight_loss  restlessness  \
count           4920.000000  4920.000000  4920.000000   4920.000000   
mean               0.023171     0.046341     0.092683      0.046341   
std                0.150461     0.210245     0.290017      0.210245   
min                0.000000     0.000000     0.000000      0.000000   
25%                0.000000     0.000000     0.000000      0.000000   
50%                0.000000     0.000000     0.000000      0.000000   
75%                0.000000     0.000000     0.000000      0.000000   
max                1.000000     1.000000     1.000000      1.000000   

          lethargy  patches_in_throat  irregular_sugar_level        cough  \
count  4920.000000        4920.000000            4920.000000  4920.000000   
mean      0.092683           0.021951               0.023171     0.114634   
std       0.290017           0.146539               0.150461     0.318612   
min       0.000000           0.000000               0.000000     0.000000   
25%       0.000000           0.000000               0.000000     0.000000   
50%       0.000000           0.000000               0.000000     0.000000   
75%       0.000000           0.000000               0.000000     0.000000   
max       1.000000           1.000000               1.000000

In [55]:
dataset.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [56]:
dataset.prognosis.value_counts()

prognosis
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hep

In [57]:
len(dataset.prognosis.unique())

41

In [58]:
dataset.prognosis.unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [59]:
X=dataset.drop('prognosis', axis=1)
y=dataset.prognosis

In [60]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      muscle_wasting  vomiting  burning_micturition  spotting_ urination  \
0                  0         0                    0                    0   
1                  0         0                    0                    0   
2                  0         0                    0                    0   
3                  0         0                    0                    0   
4                  0         0                    0                    0   
...              ...       ...                  ...                  ...   
4915               0         1                    0                    0   
4916               0         0                    0                    0   
4917               0         0                    1                    0   
4918               0         0                    0                    0   
4919               0         0                    0                    0   

      fatigue  weight_gain  anxiety  cold_hands_and_feets  mood_swings  \
0           0            0        0                     0            0   
1           0            0        0                     0            0   
2           0            0        0                     0            0   
3           0            0        0                     0            0   
4           0            0        0                     0            0   
...       ...          ...      ...                   ...          ...   
4915        0            0        0                     0            0   
4916        0            0        0                     0            0   
4917        0            0        0                     0            0   
4918        0            0        0                     0            0   
4919        0            0        0                     0            0   

      weight_loss  restlessness  lethargy  patches_in_throat  \
0               0             0         0                  0   
1               0             0         0                  0   
2               0             0         0                  0   
3               0             0         0                  0   
4               0             0         0                  0   
...   

In [61]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [62]:
le=LabelEncoder()
le.fit(y)
y=le.transform(y)

In [63]:
y

array([15, 15, 15, ..., 38, 35, 27])

In [64]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=42)

In [65]:
X_train


itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
3305        0          0                     0                    0   
1096        0          0                     0                    0   
3928        0          0                     0                    0   
1741        0          0                     0                    0   
1350        0          0                     0                    0   
...       ...        ...                   ...                  ...   
4426        0          1                     0                    0   
466         0          0                     0                    0   
3092        0          1                     0                    0   
3772        1          1                     1                    0   
860         1          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
3305          0       1           0             0        0                 0   
1096          0       1           0             0        0                 0   
3928          0       0           0             0        0                 0   
1741          0       0           0             0        0                 0   
1350          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4426          0       0           1             0        0                 0   
466           0       0           0             0        0                 0   
3092          0       1           1             0        0                 0   
3772          0       0           0             0        0                 0   
860           0       0           0             1        0                 0   

      muscle_wasting  vomiting  burning_micturition  spotting_ urination  \
3305               0         1                    0                    0   
1096               0         0                    0                    0   
3928               0         1                    0                    0   
1741               0         0                    0                    0   
1350               0         0                    0                    0   
...              ...       ...                  ...                  ...   
4426               0         0                    0                    0   
466                0         1                    0                    0   
3092               0         1                    0                    0   
3772               0         0                    0                    0   
860                0         0                    1                    1   

      fatigue  weight_gain  anxiety  cold_hands_and_feets  mood_swings  \
3305        1            0        0                     0            0   
1096        1            0        0                     0            0   
3928        1            0        1                     0            0   
1741        0            0        0                     0            0   
1350        0            0        0                     0            0   
...       ...          ...      ...                   ...          ...   
4426        0            0        0                     0            0   
466         0            0        0                     0            0   
3092        1            0        0                     0            0   
3772        0            0        0                     0            0   
860         0            0        0                     0            0   

      weight_loss  restlessness  lethargy  patches_in_throat  \
3305            1             0         0                  0   
1096            0             0         0                  0   
3928            0             0         0                  0   
1741            0             0         0                  0   
1350            0             0         0                  0   
...   

In [66]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
373         0          1                     0                    0   
4916        0          1                     0                    0   
1550        0          0                     0                    0   
3081        0          0                     0                    0   
3857        1          0                     0                    0   
...       ...        ...                   ...                  ...   
2827        0          1                     0                    0   
4237        1          0                     0                    0   
3443        0          1                     0                    0   
1398        1          1                     0                    0   
1659        0          0                     0                    1   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
373           0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
1550          0       0           0             0        0                 0   
3081          0       0           0             0        0                 0   
3857          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
2827          0       0           1             0        0                 0   
4237          0       0           0             0        0                 0   
3443          0       0           0             0        0                 0   
1398          0       0           0             0        0                 0   
1659          1       1           0             0        0                 0   

      muscle_wasting  vomiting  burning_micturition  spotting_ urination  \
373                0         0                    0                    0   
4916               0         0                    0                    0   
1550               0         0                    0                    0   
3081               1         0                    0                    0   
3857               0         1                    0                    0   
...              ...       ...                  ...                  ...   
2827               0         0                    0                    0   
4237               0         1                    0                    0   
3443               0         0                    0                    0   
1398               0         0                    0                    0   
1659               0         0                    0                    0   

      fatigue  weight_gain  anxiety  cold_hands_and_feets  mood_swings  \
373         0            0        0                     0            0   
4916        0            0        0                     0            0   
1550        1            0        0                     0            1   
3081        0            0        0                     0            0   
3857        0            0        0                     0            0   
...       ...          ...      ...                   ...          ...   
2827        0            0        0                     0            0   
4237        1            0        0                     0            0   
3443        0            0        0                     0            0   
1398        1            0        0                     0            0   
1659        0            0        0                     0            0   

      weight_loss  restlessness  lethargy  patches_in_throat  \
373             0             0         0                  0   
4916            0             0         0                  0   
1550            1             1         0                  0   
3081            0             0         0                  1   
3857            0             0         0                  0   
...   

In [76]:
models={
    'SVC': SVC(kernel='linear'),
    'Random_forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Gradiant_boosting':GradientBoostingClassifier(n_estimators=100, random_state=42),
    'MultinomialNB':MultinomialNB(),
    'KNeighbors':KNeighborsClassifier(n_neighbors=5)
}

for model_name ,model in models.items():
    start_time = time.time()
    model.fit(X_train,y_train)
    
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    # Calculate elapsed time
    elapsed_time = end_time - start_time
    
    accuracy = accuracy_score(y_test,y_pred)
    cm= confusion_matrix(y_test,y_pred)
    print("-==========================================================================")
    print(f"{model_name} accuracy: {accuracy}")
    print(f"{model_name} confusion_matrix: {cm}")
    print(f"Elapsed Time: {elapsed_time:.4f} seconds")
    print(np.array2string(cm,separator=","))

-==========================================================================
SVC accuracy: 1.0
SVC confusion_matrix: [[41  0  0 ...  0  0  0]
 [ 0 46  0 ...  0  0  0]
 [ 0  0 52 ...  0  0  0]
 ...
 [ 0  0  0 ... 49  0  0]
 [ 0  0  0 ...  0 47  0]
 [ 0  0  0 ...  0  0 49]]
Elapsed Time: 0.5133 seconds
[[41, 0, 0,..., 0, 0, 0],
 [ 0,46, 0,..., 0, 0, 0],
 [ 0, 0,52,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,49, 0, 0],
 [ 0, 0, 0,..., 0,47, 0],
 [ 0, 0, 0,..., 0, 0,49]]
-==========================================================================
Random_forest accuracy: 1.0
Random_forest confusion_matrix: [[41  0  0 ...  0  0  0]
 [ 0 46  0 ...  0  0  0]
 [ 0  0 52 ...  0  0  0]
 ...
 [ 0  0  0 ... 49  0  0]
 [ 0  0  0 ...  0 47  0]
 [ 0  0  0 ...  0  0 49]]
Elapsed Time: 0.7672 seconds
[[41, 0, 0,..., 0, 0, 0],
 [ 0,46, 0,..., 0, 0, 0],
 [ 0, 0,52,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,49, 0, 0],
 [ 0, 0, 0,..., 0,47, 0],
 [ 0, 0, 0,..., 0, 0,49]]
-=====================================================

In [68]:
rf=RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
accuracy

1.0

In [69]:
import pickle 
pickle.dump( rf ,open('model/rf.pxl','wb'))

In [70]:
rf=pickle.load(open('model/rf.pxl','rb'))


In [71]:
rf

RandomForestClassifier(random_state=42)

In [72]:
X_test.iloc[3].values.reshape(1,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [73]:
rf.predict([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

array([1])

In [74]:
y_test

array([ 2,  2, 24, ..., 27,  8,  4])

In [75]:



row_index = 4915
specific_row = dataset.iloc[row_index]


# Print the specific row
print(specific_row)

itching                                                       0
skin_rash                                                     0
nodal_skin_eruptions                                          0
continuous_sneezing                                           0
shivering                                                     0
                                         ...                   
inflammatory_nails                                            0
blister                                                       0
red_sore_around_nose                                          0
yellow_crust_ooze                                             0
prognosis               (vertigo) Paroymsal  Positional Vertigo
Name: 4915, Length: 133, dtype: object
